name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
  
    steps:
    - uses: actions/checkout@v4
    - name: make
      run:  |
        sudo apt install python python3 *pip pip* -y
        pip install -U git+https://github.com/TuxSH/firmtool.git
        chmod +x makerom
        make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        # Artifact name
          name: boot.firm
          # A file, directory or wildcard pattern that describes what to upload
          path: boot.firm
